# Generated by Django 5.0.6 on 2024-06-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
